# Generated by Django 2.0 on 2021-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dryfish', models.CharField(blank=True, max_length=100, null=True)),
                ('seafish', models.CharField(blank=True, max_length=100, null=True)),
                ('freshwater', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
