# Generated by Django 2.0 on 2021-07-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20210701_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='categoryname',
            new_name='name',
        ),
    ]
