# Generated by Django 3.2.5 on 2021-07-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20210701_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='name',
            new_name='categoryname',
        ),
    ]
