# Generated by Django 3.2.5 on 2021-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_rename_name_categorydb_categoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.DeleteModel(
            name='categorydb',
        ),
    ]
