# Generated by Django 3.2.5 on 2021-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_recipe_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('weight', models.IntegerField(max_length=50, null=True)),
                ('price', models.IntegerField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
