# Generated by Django 3.2.5 on 2021-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_product_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(max_length=50, null=True)),
            ],
        ),
    ]
