# Generated by Django 3.2.5 on 2021-09-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_customer_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='name',
            new_name='cname',
        ),
    ]
