# Generated by Django 3.2.5 on 2021-10-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_auto_20211025_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_db',
            name='instruction',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
